"""Generate examples/00-a-year-in-one-market.ipynb, the beginner entry point."""
import json, pathlib

def md(*lines): return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}
def code(*lines): return {"cell_type": "code", "metadata": {}, "execution_count": None,
                          "outputs": [], "source": list(lines)}

cells = [
md("# A year in one market\n",
   "\n",
   "This is the shortest useful thing pretium does: run a market for a\n",
   "trading year, watch one company, and see what happened to it and why.\n",
   "\n",
   "Everything here is deterministic. The same seed gives the same year,\n",
   "on any machine, forever. Nothing is downloaded and nothing is random\n",
   "in the sense of being unrepeatable.\n",
   "\n",
   "You need `pip install pretium matplotlib`. It takes about twenty\n",
   "seconds to run."),

md("## The market\n",
   "\n",
   "A universe is a roster of companies. Here one is built by hand with\n",
   "Apple's rough shape (price, share count, earnings, book value) and\n",
   "thirty-nine others are generated, so the market has something to\n",
   "co-move with. The numbers are a starting state, not a forecast: this\n",
   "is a company like Apple in a market like the US one, not Apple."),

code("import pretium as pt\n",
     "\n",
     "aapl = pt.Instrument(\n",
     "    \"AAPL\", \"technology\",\n",
     "    initial_price=75.0,          # roughly where it started 2020\n",
     "    shares_outstanding=17.77e9,\n",
     "    eps=2.97,\n",
     "    book_value_per_share=5.09,\n",
     "    avg_volume=140e6,\n",
     "    beta=1.2,\n",
     ")\n",
     "\n",
     "universe = pt.Universe([aapl])\n",
     "universe.extend(pt.Universe.random(39, seed=7))\n",
     "\n",
     "print(f\"{len(universe)} companies, fingerprint {universe.fingerprint}\")\n",
     "print(f\"model preset: {pt.ModelParams.from_preset().fingerprint}\")"),

md("The fingerprints matter more than they look. A universe fingerprint and\n",
   "a preset name and a seed are a complete description of a market: quote\n",
   "those three and anyone can reproduce your run exactly."),

md("## Two runs of the same year\n",
   "\n",
   "Both runs use the same seed, the same companies and the same calm\n",
   "baseline: the VIX pinned at 15 and corporate borrowing at 5.5%. The\n",
   "second run adds two crises and nothing else, so every difference\n",
   "between the two lines below is caused by them.\n",
   "\n",
   "Day 60 is a fear shock: the VIX jumps to 45 and decays back over three\n",
   "weeks, roughly a bad correction. Day 150 is worse: the VIX to 65 over a\n",
   "month with corporate borrowing costs up four points at the same time,\n",
   "which is fear plus a credit squeeze.\n",
   "\n",
   "A scenario pins macro state. It does not tell prices what to do: the\n",
   "crisis is an input, the market's reaction to it is not."),

code("CALM = {\"vix\": 15.0, \"corporate_bond_yield\": 0.055}\n",
     "CRISES = [\n",
     "    (\"correction\", 60, 21, 45.0, None),\n",
     "    (\"credit crunch\", 150, 30, 65.0, 0.095),\n",
     "]\n",
     "\n",
     "quiet_scenario = pt.Scenario().hold(**CALM)\n",
     "\n",
     "crisis_scenario = pt.Scenario().hold(**CALM)\n",
     "for _name, begin, over, vix_peak, yield_peak in CRISES:\n",
     "    crisis_scenario = crisis_scenario.ramp(\n",
     "        \"vix\", start=vix_peak, end=CALM[\"vix\"], over=over, begin=begin)\n",
     "    if yield_peak is not None:\n",
     "        crisis_scenario = crisis_scenario.ramp(\n",
     "            \"corporate_bond_yield\", start=yield_peak,\n",
     "            end=CALM[\"corporate_bond_yield\"], over=over, begin=begin)\n",
     "\n",
     "print(f\"day 59: {crisis_scenario.at(59)}\")\n",
     "print(f\"day 60: {crisis_scenario.at(60)}\")\n",
     "print(f\"day 150: {crisis_scenario.at(150)}\")"),

code("import pyarrow as pa, pyarrow.compute as pc\n",
     "\n",
     "def run_year(scenario, days=252):\n",
     "    engine = pt.Engine(seed=2024, universe=universe)\n",
     "    for day in range(days):\n",
     "        scenario.apply(engine, day)\n",
     "        engine.run_days(1, first_day=day, record=True)\n",
     "    return engine\n",
     "\n",
     "def daily_close(engine, ticker=\"AAPL\"):\n",
     "    \"\"\"One name's closing price per day.\"\"\"\n",
     "    bars = pa.table(engine.bars(grain=\"day\"))\n",
     "    idx = engine.tickers.index(ticker)\n",
     "    rows = pc.filter(bars, pc.equal(bars[\"instrument_id\"], idx))\n",
     "    return rows[\"close\"].to_pylist()\n",
     "\n",
     "QUIET = run_year(quiet_scenario)\n",
     "SHOCKED = run_year(crisis_scenario)\n",
     "quiet_path = daily_close(QUIET)\n",
     "shocked_path = daily_close(SHOCKED)\n",
     "\n",
     "print(f\"quiet:   {quiet_path[0]:.2f} -> {quiet_path[-1]:.2f}\")\n",
     "print(f\"crises:  {shocked_path[0]:.2f} -> {shocked_path[-1]:.2f}\")"),

md("## The picture\n",
   "\n",
   "The shaded bands are the crises. The two lines are the same company,\n",
   "the same seed and the same starting state; the only difference is that\n",
   "one market was frightened twice."),

code("import matplotlib.pyplot as plt\n",
     "\n",
     "fig, ax = plt.subplots(figsize=(11, 5))\n",
     "ax.plot(quiet_path, linewidth=1.4, label=\"no crises\", color=\"#5b8dd9\")\n",
     "ax.plot(shocked_path, linewidth=1.4, label=\"with two crises\", color=\"#c2492e\")\n",
     "\n",
     "for name, start, length, _vix, _yield in CRISES:\n",
     "    ax.axvspan(start, start + length, color=\"#c2492e\", alpha=0.10)\n",
     "    ax.axvline(start, color=\"#c2492e\", linewidth=1.0, linestyle=\"--\", alpha=0.7)\n",
     "    ax.annotate(name, xy=(start, ax.get_ylim()[1]), xytext=(start + 2, 0),\n",
     "                textcoords=\"offset points\", fontsize=9, color=\"#c2492e\",\n",
     "                va=\"top\")\n",
     "\n",
     "ax.set_xlabel(\"trading day\")\n",
     "ax.set_ylabel(\"AAPL close\")\n",
     "ax.set_title(\"One company, one year, with and without crises\")\n",
     "ax.legend(loc=\"upper left\", frameon=False)\n",
     "ax.spines[[\"top\", \"right\"]].set_visible(False)\n",
     "fig.tight_layout()\n",
     "plt.show()"),

md("## What the crises did\n",
   "\n",
   "Two numbers are worth reading off. The drawdown is how far the price\n",
   "fell from its own high, which is the loss a holder actually lives\n",
   "through. Realised volatility is how violent the ride was."),

code("import statistics as st\n",
     "\n",
     "def drawdown(path):\n",
     "    peak, worst = path[0], 0.0\n",
     "    for price in path:\n",
     "        peak = max(peak, price)\n",
     "        worst = min(worst, price / peak - 1)\n",
     "    return worst\n",
     "\n",
     "def annual_vol(path):\n",
     "    rets = [path[i] / path[i - 1] - 1 for i in range(1, len(path))]\n",
     "    return st.pstdev(rets) * 252 ** 0.5\n",
     "\n",
     "print(f\"{'':16s} {'quiet':>10s} {'with crises':>12s}\")\n",
     "print(f\"{'return':16s} {quiet_path[-1] / quiet_path[0] - 1:>10.1%} \"\n",
     "      f\"{shocked_path[-1] / shocked_path[0] - 1:>12.1%}\")\n",
     "print(f\"{'max drawdown':16s} {drawdown(quiet_path):>10.1%} \"\n",
     "      f\"{drawdown(shocked_path):>12.1%}\")\n",
     "print(f\"{'volatility':16s} {annual_vol(quiet_path):>10.1%} \"\n",
     "      f\"{annual_vol(shocked_path):>12.1%}\")"),

md("## Why the price moved\n",
   "\n",
   "A real market never tells you why. This one does, because it computed\n",
   "the reasons: every price move is a sum of named components, and they\n",
   "add up to the change exactly.\n",
   "\n",
   "Below is AAPL over the credit crunch, days 150 to 180, with each\n",
   "component's total contribution. The units are the model's internal\n",
   "mispricing scale rather than currency; the ranking and the signs are\n",
   "what to read."),

code("truth = pa.table(SHOCKED.truth())\n",
     "idx = SHOCKED.tickers.index(\"AAPL\")\n",
     "window = pc.and_(\n",
     "    pc.equal(truth[\"instrument_id\"], idx),\n",
     "    pc.and_(pc.greater_equal(truth[\"day\"], 150),\n",
     "            pc.less(truth[\"day\"], 180)),\n",
     ")\n",
     "rows = pc.filter(truth, window)\n",
     "\n",
     "# From the SECOND row on: the first row's components caused the move\n",
     "# into the window's opening price, not a move inside it.\n",
     "inside = rows.slice(1)\n",
     "totals = {name: pc.sum(inside[name]).as_py() for name in pt.Engine.FACTORS}\n",
     "for name, value in sorted(totals.items(), key=lambda kv: -abs(kv[1])):\n",
     "    print(f\"  {name:22s} {value:>+12.5f}\")\n",
     "print(f\"  {'sum':22s} {sum(totals.values()):>+12.5f}\")\n",
     "\n",
     "s_series = rows[\"mispricing_s\"].to_pylist()\n",
     "print(f\"  {'change in mispricing':22s} {s_series[-1] - s_series[0]:>+12.5f}\")"),

md("The last two numbers match, which is the point: the components are not\n",
   "an interpretation of the move, they are the move. `reversion` pulling\n",
   "against the others is the market's own pressure back toward fair\n",
   "value.\n",
   "\n",
   "`03-why-did-the-price-move.ipynb` does this properly, tick by tick."),

md("## What to read next\n",
   "\n",
   "- `01-first-simulation.ipynb` goes under the hood: the order book,\n",
   "  determinism, and how a run is made citable.\n",
   "- `04-how-realistic-is-this.ipynb` is the honest part: which statistics\n",
   "  this market matches, which it does not, and what that forbids.\n",
   "- `09-a-pandemic-shaped-market.ipynb` drives a real 2020-21 macro path\n",
   "  through the model and scores the result against what Apple did.\n",
   "\n",
   "One thing to carry forward: this market is calibrated to behave like a\n",
   "market, not to predict one. It is for testing whether a strategy or an\n",
   "agent survives conditions you choose, on a tape nobody has seen."),
]

nb = {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3",
      "language": "python", "name": "python3"},
      "language_info": {"name": "python", "version": "3.11"}},
      "nbformat": 4, "nbformat_minor": 5}
out = pathlib.Path("/Users/simoncoombes-nw/Dev/pretium/examples/00-a-year-in-one-market.ipynb")
out.write_text(json.dumps(nb, indent=1) + "\n")
print(f"wrote {out.name}: {len(cells)} cells ({sum(1 for c in cells if c['cell_type']=='code')} code)")
