"""The committed preset records agree with the library they describe.

`python/tradefloor/presets/<name>.json` is generated by `tools/presets/record.py` and read by
the documentation site. Nothing here re-measures: measuring takes a 96-core
box and twenty-six seed blocks. What these tests do is bind the record to the
package, so a record cannot quietly describe a different model than the one
installed, and `envelope.py` cannot quietly disagree with the record for the
preset it says it certifies.

That second one is the failure this file exists for. At 0.6.0 the default
moved and `envelope.CERTIFIED` was re-typed by hand from a measurement
artefact, while `DECAY_252` beside it was not and still described the
previous default. Nothing failed. The module's own docstring promises its
constants describe the shipped default, and the promise was unenforced.
"""

from __future__ import annotations

import json
import pathlib

import pytest

import tradefloor
from tradefloor import envelope

RECORDS = (pathlib.Path(__file__).resolve().parent.parent
           / "python" / "tradefloor" / "presets")

#: What `record.py` wrote. A reader that knows this number is correct about
#: every field it knows; a later schema may add fields, and adding one is not
#: a reason to fail here.
SCHEMA = 1

#: `record.py` rounds nothing, `envelope.py` publishes four places. The
#: comparison is at the published precision, because that is the claim.
PLACES = 4


def records():
    return sorted(RECORDS.glob("*.json"))


def _shipped_preset_names():
    """Every shipped preset, from the engine's own list.

    `ModelParams::preset_names()` is not on the Python surface, so it is
    read back out of the refusal that quotes it -- the same route
    `tools/calibration/preset_panel.py` takes. A hardcoded range is what
    made pt-v18 invisible to that tool for an entire era.
    """
    marker = "Shipped presets: "
    try:
        tradefloor.model_preset("pt-v0")
    except Exception as exc:
        message = str(exc)
    else:  # pragma: no cover - "pt-v0" is not a preset
        raise AssertionError("pt-v0 resolved; the refusal route is gone")
    assert marker in message, message
    names = [n.strip() for n in message.split(marker, 1)[1].split(",") if n.strip()]
    for name in names:
        assert tradefloor.model_preset(name)["name"] == name, name
    assert tradefloor.model_preset()["name"] in names
    return names


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


#: Shipped presets with NO record, against the reason, so an absence is a
#: named decision rather than a gap nobody can see.
#:
#: THIS LIST IS THE POINT. A record is the only thing that binds a preset's
#: coefficients: `test_a_record_describes_the_preset_it_names` iterates the
#: RECORDS, so a preset without one has nothing holding it to the vector it
#: was measured as. pt-v18 is how that fails in practice -- it silently
#: gained `buyback_payout_share = 1/3` inside 6326337..dccc3b0, which moved
#: its index level by 1.75 points a year and made two published figures
#: describe a preset that no longer existed. The name did not change, so
#: nothing said the model had. `coefficient_digest` exists to catch exactly
#: that and had nothing to compare against.
#:
#: A preset added here is a preset nobody is watching. Add one only with a
#: reason, and delete the entry when the record lands.
WITHOUT_RECORDS = {
    "pt-v1": "the baseline. Never the default of a release, and the frozen "
             "reference every seed sd is measured at rather than a preset "
             "anyone is asked to run",
    "pt-v2": "superseded inside an era; never shipped as a default",
    "pt-v3": "default at 0.1.0, before records existed",
    "pt-v4": "superseded inside an era; never shipped as a default",
    "pt-v5": "superseded inside an era; never shipped as a default",
    "pt-v6": "superseded inside an era; never shipped as a default",
    "pt-v7": "superseded inside an era; never shipped as a default",
    "pt-v8": "superseded inside an era; never shipped as a default",
    "pt-v9": "superseded inside an era; never shipped as a default",
    "pt-v10": "default at 0.2.0, before records existed",
    "pt-v11": "superseded inside an era; never shipped as a default",
    "pt-v12": "default at 0.3.0, before records existed",
    "pt-v13": "superseded inside an era; never shipped as a default",
    "pt-v15": "superseded inside an era; never shipped as a default",
    "pt-v18": "MEASURED BUT UNRECORDED, and the one entry here that is a "
              "live risk rather than history: it is a candidate for the "
              "default and it already changed under its own name once. Its "
              "record is blocked on the era's dial vector settling",
}


def test_every_shipped_preset_either_has_a_record_or_says_why_not():
    """An absent record is a decision, and it has to be written down.

    The one thing binding a preset's coefficients is its record, so a
    preset without one can be edited under its own name and nothing fails.
    That is not hypothetical: pt-v18 gained a dial mid-era and two
    published figures went stale silently.

    So the SET of presets without records is pinned. A new preset fails
    this test until someone either writes its record or states here why it
    does not need one, which is the moment to make that call rather than
    six weeks later.
    """
    have = {load(p)["preset"] for p in records()}
    shipped = _shipped_preset_names()
    missing = {n for n in shipped if n not in have}
    assert missing == set(WITHOUT_RECORDS), (
        f"presets with no record and no reason: {sorted(missing - set(WITHOUT_RECORDS))}; "
        f"reasons given for presets that now have a record or do not exist: "
        f"{sorted(set(WITHOUT_RECORDS) - missing)}"
    )
    # And a record for a preset this build does not ship is a record nobody
    # can check against anything.
    assert have <= set(shipped), sorted(have - set(shipped))


def test_at_least_the_shipped_default_has_a_record():
    assert records(), f"no preset records under {RECORDS}"
    names = {load(p)["preset"] for p in records()}
    assert tradefloor.model_preset()["name"] in names


@pytest.mark.parametrize("path", records(), ids=lambda p: p.stem)
def test_a_record_describes_the_preset_it_names(path):
    """The coefficient vector, not the name.

    A preset's name is a label and a label can be moved. Comparing the
    digest of the shipped coefficients against the digest in the record
    catches a record that was generated before an era boundary and kept its
    filename, which is exactly how a stale published figure survives.
    """
    from tools.presets.record import coefficient_digest  # noqa: PLC0415

    rec = load(path)
    assert rec["schema"] == SCHEMA
    assert rec["preset"] == path.stem
    shipped = tradefloor.ModelParams.from_preset(rec["preset"]).to_dict()
    assert coefficient_digest(shipped) == rec["coefficient_digest"], (
        f"{path.name} was measured on a different {rec['preset']} than this "
        "build ships. Re-measure it or restore the preset."
    )
    assert rec["coefficients"] == pytest.approx(shipped)


def test_the_envelope_agrees_with_the_record_for_the_preset_it_certifies():
    """The binding that was missing.

    `envelope.PRESET` names a preset and `CERTIFIED` and `MEASURED_504`
    publish its panel. Both are re-typed by hand at an era boundary. This
    asserts they came from the record for the preset the envelope names, at
    the precision the envelope publishes.
    """
    path = RECORDS / f"{envelope.PRESET}.json"
    assert path.exists(), (
        f"envelope.PRESET is {envelope.PRESET!r} and {path.name} does not "
        "exist, so nothing measured backs the published panel"
    )
    rec = load(path)

    for field, published in (("panel_252", envelope.CERTIFIED),
                             ("panel_504", envelope.MEASURED_504)):
        measured = rec[field]
        assert set(measured) == set(published), (
            f"{field} and the envelope disagree on WHICH statistics the "
            "panel holds"
        )
        for stat, value in published.items():
            assert value == pytest.approx(measured[stat], abs=10 ** -PLACES), (
                f"envelope publishes {stat}={value} for {envelope.PRESET}, "
                f"the record measured {measured[stat]}"
            )


def test_the_envelope_and_the_record_agree_on_the_level_and_crisis_rows():
    """The binding `CERTIFIED` had and the level and crisis rows did not.

    `CERTIFIED` and `MEASURED_504` are tied to the committed record by the
    test above, so neither can be re-typed at an era boundary and drift.
    `CERTIFIED_LEVEL` and `CERTIFIED_CRISIS` were checked only for
    MEMBERSHIP and for red/green DIRECTION -- never for value. That is the
    same hole as a preset with no record, one level down: three published
    figures with nothing holding them to a measurement.

    They are bound here to `panel_level.roster_varying`, which is the
    certified protocol, and the held reading beside it is asserted UNGRADED
    -- a level figure from the other protocol is never compared with a band
    (`facts.LEVEL_PROTOCOL["comparison_rule"]`).
    """
    from tradefloor.facts import CRISIS, LEVEL, LEVEL_PROTOCOL  # noqa: PLC0415

    rec = load(RECORDS / f"{envelope.PRESET}.json")
    block = rec.get("panel_level")
    assert block, (
        f"{envelope.PRESET} has no panel_level block, so nothing measured "
        "backs CERTIFIED_LEVEL or CERTIFIED_CRISIS. Write one with "
        "tools/presets/record.py --level-only"
    )
    varying, held = block["roster_varying"], block["roster_held"]
    assert varying["graded"] and varying["roster_per_seed"], varying
    assert not held["graded"] and not held["roster_per_seed"], (
        "the held-roster reading is marked graded; the bands belong to the "
        "roster-varying protocol and a held figure carries no verdict"
    )
    assert varying["n_seeds"] == len(LEVEL_PROTOCOL["seeds"])
    assert varying["days"] == LEVEL_PROTOCOL["days"]
    assert block["comparison_rule"] == LEVEL_PROTOCOL["comparison_rule"]
    assert set(block["rows"]) == set(LEVEL) | set(CRISIS)

    published = dict(envelope.CERTIFIED_LEVEL, **envelope.CERTIFIED_CRISIS)
    assert set(published) <= set(block["rows"])
    for stat, value in published.items():
        measured = varying[stat]["value"]
        assert value == pytest.approx(measured, abs=10 ** -PLACES), (
            f"envelope publishes {stat}={value} for {envelope.PRESET}, the "
            f"record measured {measured} on the certified protocol"
        )
        # The held reading carries no verdict, so it cannot be mistaken for
        # this one.
        assert "band" not in held[stat], stat

    # A measured figure names the commit it was measured at, because a level
    # figure with no pin cannot be checked -- pt-v18's went stale exactly
    # that way.
    assert varying["commit"] and held["commit"], block


def test_the_envelope_and_the_record_agree_on_the_band_count():
    rec = load(RECORDS / f"{envelope.PRESET}.json")
    assert rec["in_band"]["252"] == len(envelope.CERTIFIED)
    assert rec["misses"]["252"] == [], (
        "the certified preset misses a band at the certified horizon, which "
        f"is a bigger fact than a stale number: {rec['misses']['252']}"
    )
