"""The committed preset records agree with the library they describe.

`python/tradefloor/presets/<name>.json` is generated by `tools/presets/record.py` and read by
the documentation site. Nothing here re-measures: measuring takes a 96-core
box and twenty-six seed blocks. What these tests do is bind the record to the
package, so a record cannot quietly describe a different model than the one
installed, and `envelope.py` cannot quietly disagree with the record for the
preset it says it certifies.

That second one is the failure this file exists for. At 0.6.0 the default
moved and `envelope.CERTIFIED` was re-typed by hand from a measurement
artefact, while `DECAY_252` beside it was not and still described the
previous default. Nothing failed. The module's own docstring promises its
constants describe the shipped default, and the promise was unenforced.
"""

from __future__ import annotations

import json
import pathlib

import pytest

import tradefloor
from tradefloor import envelope

RECORDS = (pathlib.Path(__file__).resolve().parent.parent
           / "python" / "tradefloor" / "presets")

#: What `record.py` wrote. A reader that knows this number is correct about
#: every field it knows; a later schema may add fields, and adding one is not
#: a reason to fail here.
SCHEMA = 1

#: `record.py` rounds nothing, `envelope.py` publishes four places. The
#: comparison is at the published precision, because that is the claim.
PLACES = 4


def records():
    return sorted(RECORDS.glob("*.json"))


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def test_at_least_the_shipped_default_has_a_record():
    assert records(), f"no preset records under {RECORDS}"
    names = {load(p)["preset"] for p in records()}
    assert tradefloor.model_preset()["name"] in names


@pytest.mark.parametrize("path", records(), ids=lambda p: p.stem)
def test_a_record_describes_the_preset_it_names(path):
    """The coefficient vector, not the name.

    A preset's name is a label and a label can be moved. Comparing the
    digest of the shipped coefficients against the digest in the record
    catches a record that was generated before an era boundary and kept its
    filename, which is exactly how a stale published figure survives.
    """
    from tools.presets.record import coefficient_digest  # noqa: PLC0415

    rec = load(path)
    assert rec["schema"] == SCHEMA
    assert rec["preset"] == path.stem
    shipped = tradefloor.ModelParams.from_preset(rec["preset"]).to_dict()
    assert coefficient_digest(shipped) == rec["coefficient_digest"], (
        f"{path.name} was measured on a different {rec['preset']} than this "
        "build ships. Re-measure it or restore the preset."
    )
    assert rec["coefficients"] == pytest.approx(shipped)


def test_the_envelope_agrees_with_the_record_for_the_preset_it_certifies():
    """The binding that was missing.

    `envelope.PRESET` names a preset and `CERTIFIED` and `MEASURED_504`
    publish its panel. Both are re-typed by hand at an era boundary. This
    asserts they came from the record for the preset the envelope names, at
    the precision the envelope publishes.
    """
    path = RECORDS / f"{envelope.PRESET}.json"
    assert path.exists(), (
        f"envelope.PRESET is {envelope.PRESET!r} and {path.name} does not "
        "exist, so nothing measured backs the published panel"
    )
    rec = load(path)

    # RE-PINNED 2026-09-22, WHEN A TABLE BECAME ABLE TO PUBLISH AN ABSENCE.
    #
    # `crisis_sector_dispersion` needs thirty sessions above the crisis
    # threshold inside its window; a 252-day run of this preset holds single
    # figures, so the certification run reads the row on no seed, the median
    # panel OMITS it (`facts.aggregate_panels`'s rule for an all-empty
    # pooled row), and the envelope publishes `None` for it.
    #
    # So the binding is in three parts rather than one equality, and each
    # part fails on a different lie:
    #
    #   a row the envelope publishes a NUMBER for must be in the record and
    #   must agree -- the original check, unchanged;
    #
    #   a row the envelope publishes `None` for must be ABSENT from the
    #   record. This is the half that bites when the box re-measures: a
    #   record that gains the reading while the module still says `None` is
    #   a stale constant, which is exactly what this file exists for. Run
    #   `tools/presets/envelope_tables.py --write` and it goes green;
    #
    #   a row the record carries and the envelope does not is still a schema
    #   change and still fails.
    for field, published in (("panel_252", envelope.CERTIFIED),
                             ("panel_504", envelope.MEASURED_504)):
        measured = rec[field]
        assert set(measured) <= set(published), (
            f"{field} carries "
            f"{sorted(set(measured) - set(published))}, which the envelope "
            f"does not publish: that is a schema change, not a measurement")
        for stat, value in published.items():
            if value is None:
                assert stat not in measured, (
                    f"envelope publishes {stat} as absent for "
                    f"{envelope.PRESET} and the record measured "
                    f"{measured[stat]}. Rewrite the table from the record "
                    f"with tools/presets/envelope_tables.py --write")
                continue
            assert stat in measured, (
                f"envelope publishes {stat}={value} for {envelope.PRESET} "
                f"and the record's {field} does not carry the row")
            assert value == pytest.approx(measured[stat], abs=10 ** -PLACES), (
                f"envelope publishes {stat}={value} for {envelope.PRESET}, "
                f"the record measured {measured[stat]}"
            )


def test_the_envelope_agrees_with_the_record_on_the_level_and_crisis_rows():
    """The other two published blocks, bound the same way.

    `CERTIFIED_LEVEL` and `CERTIFIED_CRISIS` are certified on
    `facts.LEVEL_PROTOCOL`, where the roster varies with the seed. The preset
    panel holds roster 111, so no panel can produce them and nothing bound
    them to anything -- which is how `envelope.DECAY_252` came to describe
    pt-v14 under a pt-v16 default with only a comment to say so.

    `record.py --level-rows` writes them into the record from a measurement
    that carries its own control arm, and this is the binding. A record
    without the block fails here rather than being skipped: an absent block
    is exactly the state this test exists to make visible.
    """
    rec = load(RECORDS / f"{envelope.PRESET}.json")
    block = rec.get("level_protocol")
    assert block is not None, (
        f"{envelope.PRESET}.json carries no level_protocol block, so nothing "
        f"measured backs envelope.CERTIFIED_LEVEL and CERTIFIED_CRISIS. "
        f"Write one with `record.py --level-rows`."
    )
    assert block["control"]["reproduced"], (
        "the level measurement's control arm did not reproduce, so the "
        "published rows are not on the ruler they replaced")

    for field, published in (("certified_level", envelope.CERTIFIED_LEVEL),
                             ("certified_crisis", envelope.CERTIFIED_CRISIS)):
        measured = block[field]
        assert set(measured) == set(published), (
            f"{field} and the envelope disagree on WHICH rows the block holds")
        for stat, value in published.items():
            assert value == pytest.approx(measured[stat], abs=10 ** -PLACES), (
                f"envelope publishes {stat}={value} for {envelope.PRESET}, "
                f"the record measured {measured[stat]}")


def test_the_level_block_was_measured_on_the_preset_the_record_describes():
    """The block's own vector against the record's, name by name.

    A `level_protocol` block is a thirty-seed measurement on a protocol no
    panel runs, so `record.py --panel` cannot rebuild it and carries it
    forward instead. Carrying it is only honest while the preset's
    coefficient VALUES have not moved: a name ADDED to `ModelParams` is
    inert, and a value that moved is a different model wearing the same
    name, which is `restamp.py`'s rule applied to this block.

    Both halves of that went wrong at once. pt-v19's block was written from
    `b4fix10` at `2d83167`, nineteen of its coefficients moved at 31ef261,
    and then `record.py --panel` deleted the block rather than reporting it
    stale, which left `envelope.CERTIFIED_LEVEL` published with nothing
    behind it (defect-26). This is the check that fails on the first of
    those without waiting for the second.

    A block written before `level_rows.py` stamped the vector carries
    `coefficients: null` and is skipped, with the gap named rather than
    passed over in silence.
    """
    rec = load(RECORDS / f"{envelope.PRESET}.json")
    block = rec.get("level_protocol")
    assert block is not None, (
        f"{envelope.PRESET}.json carries no level_protocol block; "
        "test_the_envelope_agrees_with_the_record_on_the_level_and_crisis_rows "
        "says what to do about it")
    ran = block.get("coefficients")
    if ran is None:
        pytest.skip(
            f"{envelope.PRESET}.json's level block predates the coefficient "
            "stamp, so nothing here can tell whether the preset moved under "
            "it. Re-measure with tools/presets/level_panel.py to close this.")
    moved = sorted(k for k in set(ran) & set(rec["coefficients"])
                   if ran[k] != rec["coefficients"][k])
    assert not moved, (
        f"{len(moved)} of {envelope.PRESET}'s coefficients have moved since "
        f"its level block was measured ({', '.join(moved[:6])}), so "
        f"envelope.CERTIFIED_LEVEL and CERTIFIED_CRISIS describe a preset "
        f"that no longer exists")


def test_every_level_and_crisis_row_the_envelope_publishes_is_graded():
    """Nothing in these two blocks is published without a band to read it.

    A row here with no entry in `facts.REAL_MARKETS` would be a number in the
    certified envelope that cannot pass or fail, which `REPORTING_ONLY`
    exists to keep out.
    """
    from tradefloor.facts import REAL_MARKETS

    for table in (envelope.CERTIFIED_LEVEL, envelope.CERTIFIED_CRISIS):
        for stat in table:
            assert stat in REAL_MARKETS, (
                f"{stat} is published in the certified envelope and has no "
                f"band, so it earns no verdict")


@pytest.mark.ship_bar
def test_the_envelope_and_the_record_agree_on_the_band_count():
    """Every row the record GRADED at 252 is in band, and the count says so.

    RE-PINNED 2026-09-22, from `len(envelope.CERTIFIED)` to the record's own
    denominator. `CERTIFIED` gained `crisis_sector_dispersion` and the count
    did not, because the count is the rows TESTED and that row is neither
    tested nor failed on a run that held too few crisis sessions:
    `preset_panel._count_in_band` takes it out of both sides, the way it
    already takes a row the basis carries no band for out of both sides.

    The denominator is therefore the panel the record published, less the
    rows named unreadable on it. A row that is ABSENT is not in the panel at
    all, so it is already out; naming `len(CERTIFIED)` here would have
    asserted 14 == 15 the day the row landed and 15 == 15 the day a preset
    read it, and neither is the question. Any row the record does grade and
    misses still fails on the line below.
    """
    rec = load(RECORDS / f"{envelope.PRESET}.json")
    graded = len(rec["panel_252"]) - len(rec["unreadable"]["252"] or [])
    assert rec["in_band"]["252"] == graded, (
        f"the record grades {graded} row(s) at 252 and counts "
        f"{rec['in_band']['252']} in band")
    # And NO SHAPE ROW may be absent. A shape row is a property of the
    # returns and reads on every run -- `preset_panel._job` fetches it with
    # `p[k]` and a run that dropped one fails there -- so the only row that
    # can be missing from this panel is an `ABSENT_OK` one. This is what
    # stops the denominator above from quietly shrinking: the "14 of 14" is
    # fourteen shape rows and this asserts all fourteen are in the panel the
    # count was taken over.
    from tradefloor.facts import SHAPE

    assert set(SHAPE) <= set(rec["panel_252"]), (
        f"the record's panel_252 is missing shape row(s) "
        f"{sorted(set(SHAPE) - set(rec['panel_252']))}, so the count beside "
        f"it is not a count of the certified fourteen")
    assert rec["misses"]["252"] == [], (
        "the certified preset misses a band at the certified horizon, which "
        f"is a bigger fact than a stale number: {rec['misses']['252']}"
    )


# --------------------------------------------------------------------------
# The index tail row, through the record
#
# The row is a POOLED RATE: its graded value is two counts summed over the
# seeds, so a per-seed panel that keeps only the fourteen shape rows cannot
# produce it. These bind the path from what `preset_panel.py` keeps, through
# `envelope.certification_record`, to the field `record.py` writes -- so the
# row cannot be dropped at any of the three seams without a failure.
# --------------------------------------------------------------------------


def test_the_held_roster_tool_emits_no_index_tail_figure_and_says_why():
    """The omission is asserted, not merely observed.

    `index_tail_dn3_pct` is certified on `facts.LEVEL_PROTOCOL`, where the
    roster varies with the seed; `preset_panel.py` holds roster 111. The two
    read 1.2749 and 1.124 per cent on the shipped preset, a 13.4 per cent
    gap, so a held-roster figure carried in a preset record under this row's
    name would be compared with the certified one.

    Annotating it would not prevent that. Every ruler error this project has
    made was labelled somewhere and compared anyway: the real VIX AR1 is
    documented as a whole-span estimate and was scored against 252-day
    windows; `crisisprobe-frontier`'s tail band declares itself CHOSEN in
    its own source and still produced a charter verdict; `REAL_TAIL3 =
    107/9236` carries its provenance in `facts.py` while eight scripts
    divided GSPC hits by a VIX session count.

    So the held-roster path emits NOTHING for this row, and this test fails
    if it ever starts to. Absent with a stated reason is honest; a
    wrong-protocol number with a footnote is not.
    """
    import sys

    sys.path.insert(0, str(RECORDS.parent.parent.parent
                           / "tools" / "calibration"))
    preset_panel = pytest.importorskip("preset_panel")
    from tradefloor.facts import pooled_rate_counts

    counts = set(pooled_rate_counts(envelope.TAIL_ROW))
    kept = set(preset_panel.PANEL)
    assert envelope.TAIL_ROW not in kept
    assert not (counts & kept), (
        "the held-roster panels carry the tail row's counts, so "
        "envelope.certify will build a tail block from the wrong protocol")
    assert sorted(preset_panel.PANEL) == sorted(envelope.CERTIFIED)

    # And the reason travels in the artefact, naming both the mismatch and
    # what would fill the field.
    reason = preset_panel.TAIL_NOT_MEASURED
    assert envelope.TAIL_ROW in reason
    assert "LEVEL_PROTOCOL" in reason and "seed=111" in reason
    assert "level-protocol arm" in reason


def test_certify_finds_no_tail_block_on_held_roster_panels():
    """The omission, end to end: the tool's own panel shape yields None.

    Asserted on panels built the way `preset_panel._job` builds them --
    trimmed to `PANEL` -- so this fails if the trim ever widens to include
    the counts, which is the only way a held-roster tail figure could reach
    a record.
    """
    from tradefloor.facts import REAL_MARKETS

    import sys

    sys.path.insert(0, str(RECORDS.parent.parent.parent
                           / "tools" / "calibration"))
    preset_panel = pytest.importorskip("preset_panel")

    full = {k: (lo + hi) / 2.0 for k, (lo, hi) in REAL_MARKETS.items()}
    full["index_tail_dn3_hits"] = 3
    full["index_tail_dn3_sessions"] = 251
    # `if k in full`, since 2026-09-22. `PANEL` carries
    # `crisis_sector_dispersion`, which is deliberately NOT in
    # `REAL_MARKETS` -- the decade table has no reading for it -- and a
    # held-roster seed that held no crisis does not carry it either. A
    # fabricated value here would be this test asserting something about a
    # panel shape `_job` never produces.
    trimmed = [{k: full[k] for k in preset_panel.PANEL if k in full}
               for _ in range(4)]
    result = envelope.certify(trimmed)
    assert result["tail"] is None
    assert envelope.certification_record(result)["tail"] is None


def test_a_certification_record_carries_the_tail_block_when_the_panels_do():
    """The second seam, on panels shaped the way the tool now keeps them."""
    from tradefloor.facts import REAL_MARKETS

    panels = []
    for i in range(4):
        panel = {k: (lo + hi) / 2.0 for k, (lo, hi) in REAL_MARKETS.items()}
        panel["fear_gauge_dn3_samples"] = [panel["fear_gauge_dn3"]]
        panel["index_tail_dn3_hits"] = i
        panel["index_tail_dn3_sessions"] = 251
        panel["index_tail_dn3_pct"] = 100.0 * i / 251
        panels.append(panel)
    record = envelope.certification_record(
        envelope.certify(panels, stationary_opening=False))
    tail = record["tail"]
    assert tail["row"] == envelope.TAIL_ROW
    assert tail["hits"] == 0 + 1 + 2 + 3 and tail["sessions"] == 4 * 251
    assert tail["rate"] == pytest.approx(100.0 * 6 / 1004)
    assert tail["counted"] is False
    # JSON-safe, because this is what gets written to a record file.
    assert json.loads(json.dumps(tail)) == tail


@pytest.mark.parametrize("path", records(), ids=lambda p: p.stem)
def test_no_committed_record_carries_a_tail_figure(path):
    """The third seam, asserted rather than skipped.

    A record is written from `preset_panel.py`, which runs the held roster,
    and the row is certified on the varying one. So no record carries a tail
    figure and none should: this fails if one appears, which is the point.
    It was a conditional skip until the ruling, and a skip cannot fail --
    it would have gone quiet on exactly the regression it was written for.

    When `preset_panel.py` grows a level-protocol arm, this test is what has
    to be edited to admit the field, which puts the decision in front of
    whoever makes the change.
    """
    rec = load(path)
    tail = rec.get("mechanism_252", {}).get("tail")
    assert tail is None, (
        f"{path.name} carries a tail figure. It was measured on the held "
        "roster and the row is certified on facts.LEVEL_PROTOCOL, which "
        "reads 13.4 per cent higher on the shipped preset; a reader will "
        "compare it with envelope.CERTIFIED_CRISIS. See "
        "preset_panel.TAIL_NOT_MEASURED")


# --------------------------------------------------------------------------
# The panel measures every shipped preset
#
# `preset_panel.py` is the run that gives a preset its record, and it costs a
# 96-core box. It used to discover the preset list by counting up from pt-v1
# and stopping at the first name that did not resolve. `pt-v17` does not
# exist, so the walk stopped at sixteen on a build shipping seventeen and a
# commissioned run measured every preset EXCEPT `pt-v18` -- the one it was
# commissioned for -- and said nothing on the way, because "16 presets, 2880
# measurements" is what a correct run of a sixteen-preset build looks like.
#
# The guard belongs here rather than in the tool: the tool's own preflight
# runs on the box, twenty minutes and one wheel build after the launch.
# --------------------------------------------------------------------------


def test_the_panel_measures_every_shipped_preset():
    import sys

    sys.path.insert(0, str(RECORDS.parent.parent.parent
                           / "tools" / "calibration"))
    preset_panel = pytest.importorskip("preset_panel")

    shipped = list(tradefloor.preset_names())
    assert preset_panel.presets() == shipped, (
        "the panel would measure a different set from the one the build "
        "ships, so a preset could be missing from the run that gives it a "
        "record"
    )
    # And the difference is live rather than incidental: walk the numbering
    # the way the tool used to and, where the shipped list has a gap, the
    # walk is SHORT. Stated as a condition and not as a fact about pt-v17,
    # so shipping that number makes this fall away instead of failing.
    walked = []
    for i in range(1, len(shipped) + 2):
        name = f"pt-v{i}"
        if name not in shipped:
            break
        walked.append(name)
    if walked != shipped:
        assert preset_panel.presets() != walked, (
            "the numbering has a gap and the tool still stops at it")
