"""The committed preset records agree with the library they describe.

`python/tradefloor/presets/<name>.json` is generated by `tools/presets/record.py` and read by
the documentation site. Nothing here re-measures: measuring takes a 96-core
box and twenty-six seed blocks. What these tests do is bind the record to the
package, so a record cannot quietly describe a different model than the one
installed, and `envelope.py` cannot quietly disagree with the record for the
preset it says it certifies.

That second one is the failure this file exists for. At 0.6.0 the default
moved and `envelope.CERTIFIED` was re-typed by hand from a measurement
artefact, while `DECAY_252` beside it was not and still described the
previous default. Nothing failed. The module's own docstring promises its
constants describe the shipped default, and the promise was unenforced.
"""

from __future__ import annotations

import json
import pathlib

import pytest

import tradefloor
from tradefloor import envelope

RECORDS = (pathlib.Path(__file__).resolve().parent.parent
           / "python" / "tradefloor" / "presets")

#: What `record.py` wrote. A reader that knows this number is correct about
#: every field it knows; a later schema may add fields, and adding one is not
#: a reason to fail here.
SCHEMA = 1

#: `record.py` rounds nothing, `envelope.py` publishes four places. The
#: comparison is at the published precision, because that is the claim.
PLACES = 4


def records():
    return sorted(RECORDS.glob("*.json"))


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def test_at_least_the_shipped_default_has_a_record():
    assert records(), f"no preset records under {RECORDS}"
    names = {load(p)["preset"] for p in records()}
    assert tradefloor.model_preset()["name"] in names


@pytest.mark.parametrize("path", records(), ids=lambda p: p.stem)
def test_a_record_describes_the_preset_it_names(path):
    """The coefficient vector, not the name.

    A preset's name is a label and a label can be moved. Comparing the
    digest of the shipped coefficients against the digest in the record
    catches a record that was generated before an era boundary and kept its
    filename, which is exactly how a stale published figure survives.
    """
    from tools.presets.record import coefficient_digest  # noqa: PLC0415

    rec = load(path)
    assert rec["schema"] == SCHEMA
    assert rec["preset"] == path.stem
    shipped = tradefloor.ModelParams.from_preset(rec["preset"]).to_dict()
    assert coefficient_digest(shipped) == rec["coefficient_digest"], (
        f"{path.name} was measured on a different {rec['preset']} than this "
        "build ships. Re-measure it or restore the preset."
    )
    assert rec["coefficients"] == pytest.approx(shipped)


def test_the_envelope_agrees_with_the_record_for_the_preset_it_certifies():
    """The binding that was missing.

    `envelope.PRESET` names a preset and `CERTIFIED` and `MEASURED_504`
    publish its panel. Both are re-typed by hand at an era boundary. This
    asserts they came from the record for the preset the envelope names, at
    the precision the envelope publishes.
    """
    path = RECORDS / f"{envelope.PRESET}.json"
    assert path.exists(), (
        f"envelope.PRESET is {envelope.PRESET!r} and {path.name} does not "
        "exist, so nothing measured backs the published panel"
    )
    rec = load(path)

    for field, published in (("panel_252", envelope.CERTIFIED),
                             ("panel_504", envelope.MEASURED_504)):
        measured = rec[field]
        assert set(measured) == set(published), (
            f"{field} and the envelope disagree on WHICH statistics the "
            "panel holds"
        )
        for stat, value in published.items():
            assert value == pytest.approx(measured[stat], abs=10 ** -PLACES), (
                f"envelope publishes {stat}={value} for {envelope.PRESET}, "
                f"the record measured {measured[stat]}"
            )


def test_the_envelope_and_the_record_agree_on_the_band_count():
    rec = load(RECORDS / f"{envelope.PRESET}.json")
    assert rec["in_band"]["252"] == len(envelope.CERTIFIED)
    assert rec["misses"]["252"] == [], (
        "the certified preset misses a band at the certified horizon, which "
        f"is a bigger fact than a stale number: {rec['misses']['252']}"
    )
