//! Bit-identical parity for `fair_value`, against the reference implementation.
//!
//! **This is a hard gate, not evidence.** The reference implementation's
//! fair-value module has zero transcendental calls, so every operation is exactly specified by IEEE-754
//! and every implementation must agree. That is the opposite of the
//! `mathx`/RNG situation, where Chrome, Firefox and Safari disagree with each
//! other and exact parity is unattainable — see the determinism notes.
//!
//! So any mismatch here is a bug in the port, and the test asserts rather than
//! reports.
//!
//! Vectors: `goldens/fairvalue.json`, generated by the reference
//! implementation's fair-value generator. They must
//! never be regenerated from the Rust — that would make the port its own
//! oracle and the gate meaningless.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use pretium::fair_value::{
    compute_fair_value, compute_target_pe, CompanyValuationInputs, EconomyValuationInputs,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Vectors {
    meta: Meta,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    #[serde(rename = "sectorAnchors")]
    sector_anchors: HashMap<String, f64>,
}

#[derive(Deserialize)]
struct Case {
    note: String,
    #[serde(rename = "in")]
    inputs: Inputs,
    #[serde(rename = "computeFairValue")]
    fair_value: ExpectedFairValue,
    #[serde(rename = "computeTargetPE")]
    target_pe: ExpectedTargetPe,
}

#[derive(Deserialize)]
struct Inputs {
    sector: String,
    eps: Option<String>,
    #[serde(rename = "bookValuePerShare")]
    book_value_per_share: Option<String>,
    #[serde(rename = "revenueGrowth")]
    revenue_growth: Option<String>,
    #[serde(rename = "corporateBondYield")]
    corporate_bond_yield: Option<String>,
    #[serde(rename = "federalFundsRate")]
    federal_funds_rate: String,
    #[serde(rename = "qePeBoost")]
    qe_pe_boost: Option<String>,
}

#[derive(Deserialize)]
struct ExpectedFairValue {
    #[serde(rename = "fairValue")]
    fair_value: String,
    #[serde(rename = "targetPE")]
    target_pe: String,
    #[serde(rename = "sectorAnchorPE")]
    sector_anchor_pe: String,
    #[serde(rename = "rateAdjustment")]
    rate_adjustment: String,
    #[serde(rename = "qeAdjustment")]
    qe_adjustment: String,
    #[serde(rename = "bookValuePath")]
    book_value_path: bool,
}

#[derive(Deserialize)]
struct ExpectedTargetPe {
    #[serde(rename = "targetPE")]
    target_pe: String,
    #[serde(rename = "sectorAnchorPE")]
    sector_anchor_pe: String,
    #[serde(rename = "rateAdjustment")]
    rate_adjustment: String,
    #[serde(rename = "qeAdjustment")]
    qe_adjustment: String,
}

fn f(hex: &str) -> f64 {
    f64::from_bits(u64::from_str_radix(hex, 16).expect("bad bit pattern"))
}
fn opt(hex: &Option<String>) -> Option<f64> {
    hex.as_deref().map(f)
}

/// Compare on RAW BITS. A decimal comparison can agree while the doubles
/// differ, which is the failure this whole gate exists to catch.
fn same(label: &str, note: &str, got: f64, want_hex: &str) -> Option<String> {
    let want = f(want_hex);
    // NaN is exempt from BIT equality: sign and payload are unspecified by
    // both IEEE-754 and ECMAScript and differ by architecture (x86 produces
    // `fff8…`, AArch64 `7ff8…`). Neither is observable from JavaScript, so
    // requiring them to match would assert a non-fact and fail on another
    // machine. "Both are NaN" is the whole of the contract — and it is a real
    // contract here: the corpus deliberately includes NaN inputs precisely
    // because `f64::max` would launder them into plausible prices.
    if got.to_bits() == want.to_bits() || (got.is_nan() && want.is_nan()) {
        return None;
    }
    Some(format!(
        "{note}\n      {label}: rust={got:?} ({:016x})  ts={want:?} ({want_hex})",
        got.to_bits()
    ))
}

#[test]
fn matches_typescript_bit_for_bit() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("goldens/fairvalue.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e}\nRegenerate from the reference implementation's fair-value generator",
            path.display()
        )
    });
    let vectors: Vectors = serde_json::from_str(&raw).expect("malformed fairvalue.json");

    let mut failures: Vec<String> = Vec::new();

    for case in &vectors.cases {
        // The sector table stays in the reference implementation; the crate takes the anchor
        // as an input rather than owning a second copy of those numbers.
        let anchor = vectors
            .meta
            .sector_anchors
            .get(&case.inputs.sector)
            .copied()
            .unwrap_or_else(|| panic!("unknown sector {}", case.inputs.sector));

        let company = CompanyValuationInputs {
            sector_avg_pe: Some(anchor),
            eps: opt(&case.inputs.eps),
            book_value_per_share: opt(&case.inputs.book_value_per_share),
            revenue_growth: opt(&case.inputs.revenue_growth),
        };
        let economy = EconomyValuationInputs {
            corporate_bond_yield: opt(&case.inputs.corporate_bond_yield),
            federal_funds_rate: f(&case.inputs.federal_funds_rate),
            qe_pe_boost: opt(&case.inputs.qe_pe_boost),
        };

        let fv = compute_fair_value(&company, &economy);
        let e = &case.fair_value;
        for problem in [
            same("fairValue", &case.note, fv.fair_value, &e.fair_value),
            same("targetPE", &case.note, fv.target_pe, &e.target_pe),
            same(
                "sectorAnchorPE",
                &case.note,
                fv.sector_anchor_pe,
                &e.sector_anchor_pe,
            ),
            same(
                "rateAdjustment",
                &case.note,
                fv.rate_adjustment,
                &e.rate_adjustment,
            ),
            same(
                "qeAdjustment",
                &case.note,
                fv.qe_adjustment,
                &e.qe_adjustment,
            ),
        ]
        .into_iter()
        .flatten()
        {
            failures.push(problem);
        }
        if fv.book_value_path != e.book_value_path {
            failures.push(format!(
                "{}\n      bookValuePath: rust={} ts={}",
                case.note, fv.book_value_path, e.book_value_path
            ));
        }

        // computeTargetPE is exported and called directly by the market module, so it
        // is part of the contract in its own right — including on the book
        // path, where compute_fair_value discards it but callers may not.
        let pe = compute_target_pe(&company, &economy);
        let t = &case.target_pe;
        for problem in [
            same(
                "computeTargetPE.targetPE",
                &case.note,
                pe.target_pe,
                &t.target_pe,
            ),
            same(
                "computeTargetPE.sectorAnchorPE",
                &case.note,
                pe.sector_anchor_pe,
                &t.sector_anchor_pe,
            ),
            same(
                "computeTargetPE.rateAdjustment",
                &case.note,
                pe.rate_adjustment,
                &t.rate_adjustment,
            ),
            same(
                "computeTargetPE.qeAdjustment",
                &case.note,
                pe.qe_adjustment,
                &t.qe_adjustment,
            ),
        ]
        .into_iter()
        .flatten()
        {
            failures.push(problem);
        }
    }

    println!(
        "checked {} cases x 10 values = {} bit-exact comparisons",
        vectors.cases.len(),
        vectors.cases.len() * 10
    );

    assert!(
        failures.is_empty(),
        "{} mismatches against the reference implementation:\n\n  {}",
        failures.len(),
        failures.join("\n\n  ")
    );
}
