//! Phase 1 — does the deterministic maths layer actually match V8?
//!
//! Phase 0 proved `std::cos` diverges from V8 on ONE input and that `libm`
//! matched there. One input proves divergence exists; it does not prove the fix
//! generalises. This checks all 12,625 recorded V8 values, generated by
//! `scripts/rust-port/mathx-vectors.ts` from the domains the engine actually
//! visits (see the float-operation inventory in the surface audit).
//!
//! The comparison is on raw bit patterns. A decimal comparison can agree while
//! the doubles differ, which is precisely the failure this layer prevents.
//!
//! The test prints a per-function table of how BOTH `std` and `libm` compare to
//! V8, because "libm passes" is much less useful than knowing where `std` would
//! have failed and by how much. That table is the evidence for the crate-wide
//! no-`std`-transcendentals rule.

use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct File {
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    #[serde(rename = "fn")]
    function: String,
    domain: String,
    #[serde(default)]
    inputs: Option<Vec<String>>,
    #[serde(default)]
    pairs: Option<Vec<[String; 2]>>,
    outputs: Vec<String>,
}

fn parse_bits(hex: &str) -> f64 {
    f64::from_bits(u64::from_str_radix(hex, 16).expect("bad bit pattern"))
}

/// Distance in representable doubles. `to_bits` is monotonic for same-sign
/// finite values, so subtracting the patterns counts the steps between them.
fn ulp_distance(a: f64, b: f64) -> u64 {
    if a.to_bits() == b.to_bits() {
        return 0;
    }
    if a.is_nan() || b.is_nan() {
        return u64::MAX;
    }
    let ai = if a.is_sign_negative() {
        i64::MIN.wrapping_sub(a.to_bits() as i64)
    } else {
        a.to_bits() as i64
    };
    let bi = if b.is_sign_negative() {
        i64::MIN.wrapping_sub(b.to_bits() as i64)
    } else {
        b.to_bits() as i64
    };
    (ai - bi).unsigned_abs()
}

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens/mathx-v8.json")
}

#[derive(Default, Clone, Copy)]
struct Stats {
    exact: usize,
    total: usize,
    worst_ulps: u64,
}

impl Stats {
    fn record(&mut self, got: f64, want: f64) {
        self.total += 1;
        let d = ulp_distance(got, want);
        if d == 0 {
            self.exact += 1;
        }
        self.worst_ulps = self.worst_ulps.max(d);
    }
}

/// Evaluate one vector set under both implementations.
fn evaluate(v: &Vector) -> (Stats, Stats) {
    let mut std_stats = Stats::default();
    let mut libm_stats = Stats::default();

    if let Some(pairs) = &v.pairs {
        assert_eq!(
            pairs.len(),
            v.outputs.len(),
            "{}: length mismatch",
            v.function
        );
        for (pair, want_hex) in pairs.iter().zip(&v.outputs) {
            let base = parse_bits(&pair[0]);
            let exponent = parse_bits(&pair[1]);
            let want = parse_bits(want_hex);
            std_stats.record(base.powf(exponent), want);
            libm_stats.record(pretium::mathx::pow(base, exponent), want);
        }
        return (std_stats, libm_stats);
    }

    let inputs = v
        .inputs
        .as_ref()
        .unwrap_or_else(|| panic!("{}: no inputs", v.function));
    assert_eq!(
        inputs.len(),
        v.outputs.len(),
        "{}: length mismatch",
        v.function
    );

    for (in_hex, want_hex) in inputs.iter().zip(&v.outputs) {
        let x = parse_bits(in_hex);
        let want = parse_bits(want_hex);
        let (std_val, libm_val) = match v.function.as_str() {
            "exp" => (x.exp(), pretium::mathx::exp(x)),
            "log" => (x.ln(), pretium::mathx::log(x)),
            "sin" => (x.sin(), pretium::mathx::sin(x)),
            "cos" => (x.cos(), pretium::mathx::cos(x)),
            "sqrt" => (x.sqrt(), pretium::mathx::sqrt(x)),
            other => panic!("unhandled function {other}"),
        };
        std_stats.record(std_val, want);
        libm_stats.record(libm_val, want);
    }
    (std_stats, libm_stats)
}

/// Reports how `std` and `libm` each compare to Chrome's V8. **Informational —
/// it does not assert a match, and must not.**
///
/// The first version of this test asserted exact equality with V8 and failed.
/// Investigating why produced the finding that reframed the project: there is
/// no single "V8 answer" to match, because the reference runs in whatever browser
/// the player has, and the three major engines do not agree with each other.
/// See the determinism notes.
///
/// So a mismatch here is data, not a defect. What the crate must guarantee is
/// in `implementation_is_deterministic` below.
#[test]
fn report_divergence_against_v8() {
    let raw = fs::read_to_string(vectors_path())
        .expect("mathx-v8.json missing — run: npx tsx scripts/rust-port/mathx-vectors.ts");
    let file: File = serde_json::from_str(&raw).expect("malformed mathx-v8.json");

    println!();
    println!(
        "{:<6} {:>6}  {:>16}  {:>16}   domain",
        "fn", "n", "std vs V8", "libm vs V8"
    );
    println!("{}", "-".repeat(96));

    let mut failures: Vec<String> = Vec::new();
    let mut grand_total = 0usize;

    for v in &file.vectors {
        let (s, l) = evaluate(v);
        grand_total += l.total;

        let fmt = |st: Stats| {
            if st.exact == st.total {
                "exact".to_string()
            } else {
                format!("{} off, {}ulp", st.total - st.exact, st.worst_ulps)
            }
        };

        println!(
            "{:<6} {:>6}  {:>16}  {:>16}   {}",
            v.function,
            l.total,
            fmt(s),
            fmt(l),
            v.domain
        );

        if l.exact != l.total {
            failures.push(format!(
                "{} ({}): {} of {} values differ from V8, worst {} ULP",
                v.function,
                v.domain,
                l.total - l.exact,
                l.total,
                l.worst_ulps
            ));
        }
    }

    println!("{}", "-".repeat(96));
    println!("{grand_total} reference values checked against V8");
    println!();

    // Deliberately NOT an assertion. Chrome is one engine among three and the
    // three disagree; matching it exactly would mean matching Chrome players
    // while diverging from Firefox and Safari ones, which is not a coherent
    // goal. See the determinism notes.
    if failures.is_empty() {
        println!("libm reproduces Chrome/V8 exactly on every sampled input.");
    } else {
        println!("libm differs from Chrome/V8 on some inputs (all 1 ULP):");
        for f in &failures {
            println!("  {f}");
        }
        println!("\nExpected, and not a failure. See the determinism notes.");
    }
}

/// **The guarantee this crate actually makes.**
///
/// Not "matches V8" — that target does not exist, because Chrome, Firefox and
/// Safari disagree with each other on `Math.cos`. The guarantee is that
/// `mc-engine-core` returns the same bits for the same input, always, on every
/// platform it compiles for. That is what makes a seed mean something.
///
/// `libm` is pure Rust with no platform dependency, so this holds by
/// construction. Pinning it here means a future "optimisation" back to `std` —
/// which delegates to whatever libm the OS ships — fails loudly rather than
/// silently desynchronising markets between operating systems.
#[test]
fn implementation_is_deterministic() {
    let raw = fs::read_to_string(vectors_path()).expect("mathx-v8.json missing");
    let file: File = serde_json::from_str(&raw).expect("malformed mathx-v8.json");

    for v in &file.vectors {
        if let Some(pairs) = &v.pairs {
            for pair in pairs {
                let (b, e) = (parse_bits(&pair[0]), parse_bits(&pair[1]));
                let first = pretium::mathx::pow(b, e);
                for _ in 0..3 {
                    assert_eq!(
                        pretium::mathx::pow(b, e).to_bits(),
                        first.to_bits(),
                        "pow({b}, {e}) is not stable across calls"
                    );
                }
            }
            continue;
        }
        for in_hex in v.inputs.as_ref().expect("no inputs") {
            let x = parse_bits(in_hex);
            let f = |x: f64| match v.function.as_str() {
                "exp" => pretium::mathx::exp(x),
                "log" => pretium::mathx::log(x),
                "sin" => pretium::mathx::sin(x),
                "cos" => pretium::mathx::cos(x),
                "sqrt" => pretium::mathx::sqrt(x),
                other => panic!("unhandled {other}"),
            };
            let first = f(x);
            for _ in 0..3 {
                assert_eq!(
                    f(x).to_bits(),
                    first.to_bits(),
                    "{}({x}) is not stable across calls",
                    v.function
                );
            }
        }
    }
}

/// Guards the crate-wide rule by grepping the source.
///
/// A convention that depends on everyone remembering is not a rule, and the
/// failure mode here is silent — a stray `x.exp()` would compile, pass every
/// unit test, and only reveal itself as a market that slowly drifts away from
/// the TypeScript. Cheaper to make it a test.
#[test]
fn no_std_transcendentals_outside_mathx() {
    // Recursive. The first version of this walked `src/` with `read_dir`,
    // which yields `src/market` and `src/economy` as DIRECTORIES — whose
    // extension is not "rs", so they were skipped. That silently excluded 11
    // of the crate's 21 source files, including every market and economy
    // module, and it is how four `f64::max` calls in `fair_value.rs` reached
    // a supposedly-guarded crate.
    //
    // A guard that exists so nobody has to remember has to actually look
    // everywhere.
    fn collect(dir: &std::path::Path, out: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("cannot read {dir:?}: {e}")) {
            let path = entry.expect("bad dir entry").path();
            if path.is_dir() {
                collect(&path, out);
            } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                out.push(path);
            }
        }
    }

    let src = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src");
    let banned = [
        ".exp()", ".ln()", ".powf(", ".powi(", ".sin()", ".cos()",
        // `f64::max`/`min` are NOT `Math.max`/`Math.min`: Rust treats NaN as
        // missing and returns the other operand, JavaScript propagates it.
        // That launders a poisoned input into a plausible number, which is
        // the worst way to lose a NaN — so they are banned on the same
        // footing as the transcendentals.
        ".max(", ".min(",
    ];

    let mut files = Vec::new();
    collect(&src, &mut files);
    assert!(
        files.len() > 15,
        "only found {} source files — the walk is not recursive again",
        files.len()
    );

    let mut offenders = Vec::new();
    for path in &files {
        // mathx.rs is where the exceptions live, by design.
        if path.file_name().and_then(|f| f.to_str()) == Some("mathx.rs") {
            continue;
        }
        let text = fs::read_to_string(path).expect("cannot read source file");
        let mut in_tests = false;
        for (i, line) in text.lines().enumerate() {
            // `#[cfg(test)]` blocks are exempt: a test may reason about the
            // difference deliberately, and several do.
            if line.trim_start().starts_with("#[cfg(test)]") {
                in_tests = true;
            }
            if in_tests {
                continue;
            }
            let code = line.split("//").next().unwrap_or("");
            for pattern in &banned {
                if code.contains(pattern) {
                    // Integer `max`/`min` are fine — only floats diverge.
                    if (*pattern == ".max(" || *pattern == ".min(")
                        && (code.contains("levels.max(") || code.contains("len().max("))
                    {
                        continue;
                    }
                    offenders.push(format!(
                        "{}:{}: {} — use crate::mathx instead",
                        path.strip_prefix(&src).unwrap_or(path).to_string_lossy(),
                        i + 1,
                        pattern
                    ));
                }
            }
        }
    }

    println!("scanned {} source files under src/", files.len());
    assert!(
        offenders.is_empty(),
        "std transcendentals or NaN-swallowing max/min found outside mathx.rs:
  {}

         These break both V8 parity and cross-platform determinism.          See src/mathx.rs.",
        offenders.join("
  ")
    );
}
