# BuildKit reads this (not a root .dockerignore) for `-f deploy/Dockerfile`.
# The build needs pyproject.toml, the licences, README.md, rust/ (sources and
# manifests) and python/. Everything else stays out of the context, above all
# rust/goldens (135 MB of parity vectors) and any local build output.
**
!pyproject.toml
!README.md
!LICENSE-APACHE
!LICENSE-MIT
!NOTICE
!rust/Cargo.toml
!rust/Cargo.lock
!rust/README.md
!rust/LICENSE-APACHE
!rust/LICENSE-MIT
!rust/NOTICE
!rust/src/**
!python/**
!deploy/requirements-hosted.txt
python/**/__pycache__
python/tradefloor/*.so
python/tradefloor/*.pyd
python/tradefloor/*.dylib
python/tradefloor/*.pdb
